### ISSUE TITLE
Conditions on arguments of isStrongFermatPP 

### ISSUE THREAD

**Issue by grandpascorpion** [cartazio/arithmoi#25]
Hi,

isStrongFermatPP  4 9 returns True, meaning base 9 is a "strong liar" for 4
I discovered this accidentally today. I checked the definition and the algorithm seems to only work properly for odd integers > 3.

For n=1: It hung.
For n=2 and  3: It returned False for some bases

I suggest there be a hidden pre-condition function called within 
isStrongFermatPP and millerRabinV (and perhaps the "new" function)
Then,  an underlying function (isStrongFermatPP') would be called if it's a suitable candidate for Miller-Rabin.  Also, isPrime works for negative or positive integers.  I think isStrongFermatPP and related should as well.

-Fred

**Comment by Bodigrim** [comment]
Documentation says:
> isStrongFermatPP n b tests whether n is a strong Fermat probable prime for base b, where n > 2 and 1 < b < n. The conditions on the arguments are not checked.

`isStrongFermatPP 4 9` violates condition `b < n`, so its behaviour is undefined. Same for `isStrongFermatPP` with `n=1` and `n=2`. Further, `isStrongFermatPP 3 b` is `True` for the only valid value of `b=2`.

However, I do not share an opinion of original author of `arithmoi` about unchecked conditions here and there. IMHO it is almost always worth to add guards, at least when unfiltered input data can cause hangs (as `n=1` in your example). If it is possible to lift obscure restrictions on function arguments without significant performance degradation - it should be done. API must incapsulate inner mechanics as much as possible.

> Also, isPrime works for negative or positive integers. I think isStrongFermatPP and related should as well.

This is controversial. Personally I dislike the behaviour of `isPrime` in the first place. Let us leave it as is for now.

**Comment by cartazio** [comment]
Indeed.  Undefined behavior is not math. And as long as a branch is either
heavily biased so branch predictors work well for its not an innner loop,
branches are a OK.

Our plan for the next release is to try and limit changes to accepting new
algorithms that provided they have some reasonable basic testing and
perhaps benchmarks plus shoring up the soundness and testing of preexisting
parts, which Andrew is doing a heroic job of.

Phrased differently: we want to make sure that there's at least one rock
solid release that's easy for folks with old code to adapt to, and ideally
a minor version bump (though it may have to be a major version number).
That said , I could be missing some context in this thread :)

To step back and zoom out a teeny bit, when we talk about perhaps exposing
internal api components, it would be helpful (at least to me), if we can
articulate what solution concept that code is providing and why it should
be exposed , for reasons algorithmic or otherwise.  It seems like the
current conversation is honing in on that, and I like that.

Merry evening all!

**Comment by grandpascorpion** [comment]
Hi guys,

I should have checked the documentation before responding about
isStrongFermatPP.
 (Some implementation do allow b > n.  That minimal base set discussion
from the issue required that functionality)

Is it fair to say in Haskell, people generally follow this rule of thumb?
...

func n b has screens the input and calls func' n b to do the work.
Anyone calling func' (if it were exposed in the module) would know by
convention that the input is unchecked.

If funcList n lst had to repeatedly call func, it would call func' for
performance reasons (to avoid n being repeatedly validated).

I agree with you about isPrime, Andrew.  isPrime should be fixed (at some
point) rather than isStrongFermatPP.

Thanks for your insight,
Fred

**Comment by Bodigrim** [comment]
The rule of thumb in Haskell is to express required invariants on type level. In such case 1) one cannot use function incorrectly by construction, 2) one can skip reading manual entirely and rely only on type signature. Some invariants are easier to encode (e. g., use `Natural` instead of `Integer` when the number is required to be non-negative), some are harder - that is the case of `isStrongFermatPP` (I wonder whether Liquid Haskell may come handy).

Regarding safe and unsafe functions. The common pattern is to have a module `Package.Module` with function `func` and a separate module `Package.Module.Internal` with function `unsafeFunc`, where `func` performs all necessary checks and calls `unsafeFunc`.

**Comment by cartazio** [comment]
Indeed.  That is a good rough summary of modern style.  It is worth noting
that sometimes pushing checks from runtime to type checking time is often
not worth the cost if it's in a public interface that becomes harder to
use/unusable by target users.

That said, it would be fascinating to explore this for helping improve
future major revisions.

@bodigrim let's maybe talk about some examples to explore this.  I'm
flexible this week cause I'm on vacation.

**Comment by grandpascorpion** [comment]
Thanks, guys.

The reason why asked was that I  followed the "prime" convention, but not consistently.

Being new to Haskell, I followed it as well in my own canon library which is built on top of arithmoi.  It hasn't been released yet though.  I'll adopt the "unsafe" convention instead.

**Comment by Bodigrim** [comment]
Let us come to conclusion. Do we all agree to add precondition checks `n > 2` and `1 < b < n` to `isStrongFermatPP`? As for me, it is a reasonable change, preventing users' confusion.

**Comment by cartazio** [comment]
Let's only allow well defined stuff and throw useful errors otherwise :)

**Comment by cartazio** [comment]
I think we don't want to commit to exposing / being stable with respect to any details that are accidents of how things are specifically implemented.

**Comment by Bodigrim** [comment]
Looks like a good task for first timers. @grandpascorpion do you want to contribute? I can guide through the process.

**Comment by grandpascorpion** [comment]
Sure, Andrew.  Thanks for the offer.

**Comment by Bodigrim** [comment]
Fixed and merged: now `isStrongFermatPP ` does not loop forever, if its arguments do not satisfy preconditions.
