### ISSUE TITLE
sieve design and performance experiments

### ISSUE THREAD

**Issue by cartazio** [cartazio/arithmoi#36]
@ExpHP @Bodigrim  lets talk out concrete ideas / types / experiments / data structures for fancy  nice sieving here :)

**Comment by ExpHP** [comment]
Hm, I can't claim to know too much about the topic beyond what I've messed with in my free time!  But to toss around a couple of ideas:

---

When implementing factor sieves in imperative languages, I've found that for best performance in construction one does need to take the bare metal into account; [here in rust](https://gist.github.com/ExpHP/c081842d1daf947bba51ce465716a734#file-factor_sieve-rs-L127-L251) I experimented with adapting the [segmented sieve of eratosthenes](http://primesieve.org/segmented_sieve.html) method to factor sieves, and I see about a factor of 4 speedup over a non-segmented style.

It appears to me that arithmoi currently takes memory access patterns into account for the prime sieve, but not for the factor sieve. (not 100% sure)

---

On possible breaking changes to the API, I must admit I am astounded that sieveFactor and sieveIsPrime use fallback mechanisms when the number exceeds the limit.  To be honest, I feel that the trial division loop I fixed in #35 is an unnecessary bit of complexity that ought not exist in the first place!

I'm not sure whether this is simply part of "the Haskell way" (it certainly does make quickcheck style tests easier to write), or if the trial division loop was part of the goal in itself (i.e. is it faster enough than curve factorization that somebody would want to take advantage of it?).

Personally I would like to see the current capabilities of `sieveFactor` broken up:

```haskell
{- user-friendly methods -}

-- Like the current sieveFactor, but implemented in terms of the functions below.
-- As far as the user is concerned, just a faster 'factorise'.
factoriseWithSieve :: FactorSieve -> Integer

{- methods for those who like to be in control -}

-- out of bounds: Nothing
-- otherwise: same output as factorise
fsFactor :: FactorSieve -> Integer -> Maybe [(Int,Integer)]

-- If trial division from the sieve really does beat curves, this could exist:
fsSmallFactors :: FactorSieve -> Integer -> ([(Integer, Int)], Maybe Integer)
fsSmallFactors fs x = maybe (doTrialDiv x) (fsFactor sieve) x
 where doTrialDiv = ...
```

But all of this should be taken with a grain of salt, as I know little of Haskell API conventions/expectations.

---
Something I would find *really awesome* would be a way to generalize the notion of a ___ sieve.
I.e. if the totient and carmichael sieves could be described as the application of some sort of folding function over a factor sieve.

A vague-ish idea of what I'm thinking of:

```haskell
fsScan :: ([(Integer,Int)] -> b) -> FactorSieve -> SomethingSieve b
```

which would have an improved algorithmic complexity over `fmap (f.fsFactor) [1..]`.

That said, I am only dreaming.  There would be far too many details to iron out to make this feasible...

**Comment by cartazio** [comment]
This is good.  Keep on spit balling ideas or fuzzy things, I'm happy to
help be a filter / lense, but first enumerating directions to take is
useful before picking one or some!

**Comment by Bodigrim** [comment]
> Something I would find really awesome would be a way to generalize the notion of a ___ sieve.
I.e. if the totient and carmichael sieves could be described as the application of some sort of folding function over a factor sieve.
> A vague-ish idea of what I'm thinking of:
```
fsScan :: ([(Integer,Int)] -> b) -> FactorSieve -> SomethingSieve b
```

Yes, this is a good idea. We have a [special type](https://github.com/cartazio/arithmoi/blob/master/Math/NumberTheory/ArithmeticFunctions/Class.hs#L42-L47) for arithmetic functions to use instead of `[(Integer,Int)] -> b`. 

The common problem in number theory is to compute the values of the arithmetic function on the given interval (and then sum them up). That is what sieves are born to. I have once implemented such stuff in C, but source code is elsewhere. One can look at Listing 1 at page 4 of [my paper](https://arxiv.org/pdf/1305.1639v3.pdf) and the discussion below.
