### ISSUE TITLE
Split Math.NumberTheory.Logarithms into separate package

### ISSUE THREAD

**Issue by phadej** [cartazio/arithmoi#45]
So people can depend on it. Unfortunately for some `arithmoi` seems to be "heavy" dependency.
E.g. `scientific` has an internal copy.

I could setup the package (and transfer to you / be co-maintainer, if you want), and make PR here to use it, if the proposal is ok.

**Comment by cartazio** [comment]
I think we're first focusing on getting the code base in great shape and
such before anything like that is on the table

**Comment by Bodigrim** [comment]
It could possibly make sense, because logarithms does not intertwine with number theory much. I  think I can spend a day or two in January getting `Math.NumberTheory.Logarithms` in shape. However, I am not sure that, for instance, maintainers of `scientific` would be keen to switch from their internal copy to the new hypothetical package.

**Comment by phadej** [comment]
@Bodigrim I made http://hackage.haskell.org/package/integer-logarithms already, there's also a PR for `scientific`, just in case.

**Comment by cartazio** [comment]
Only integer log?

Obviously there's a lack of explicit branchcut complex logs 😱👹. @bodigrim
that would fix the number theory relevancy right? :)

**Comment by phadej** [comment]
And it got merged: https://github.com/basvandijk/scientific/pull/45 in `scientific`

**Comment by Bodigrim** [comment]
Since `integer-logarithms` got included into `scientific`, it looks utterly unreasonable to keep our own copy. That would mean **three** triplicates of code floating around :D It would also free `arithmoi` from a pack of low-level unboxed/CPP stuff.

@phadej could you please transfer me the ownership, as you have generously offered?

**Comment by phadej** [comment]
@Bodigrim, sorry I don't understand, transfer the repository to your account? I have no objections, will do so, if it's the intention.

Out of curiosity, what's the third copy, `arithmoi` and `scientific` and ?

**Comment by Bodigrim** [comment]
Yes, please, if you do not mind. This will make things a bit easier for me. 

I meant old `scientific`, new `integer-logarithms` and `arithmoi` - that was three.

**Comment by phadej** [comment]
Hmm, I don't understand what's the difference, but if you wish.

**Comment by phadej** [comment]
To be sure, I hope that `integer-logarithms` will be consider "ready" and only "maintaining" be performed (so it works with newer GHC etc), epsecially no "explicit branchcut complex log" added etc.

**Comment by phadej** [comment]
Also made a revision so the urls are right: http://hackage.haskell.org/package/integer-logarithms/revisions (failed at first).
