### ISSUE TITLE
Generate a list of numbers with given prime divisors

### ISSUE THREAD

**Issue by Bodigrim** [cartazio/arithmoi#78]
It would be nice to have a function, which lists numbers with prime divisors in a given set. Here is a very inefficient implementation:

```haskell
foo :: Set Integer -> Integer -> Integer -> [Integer]
foo ps from to = filter (all (flip S.member ps . fst) . factorise) [from..to]
```

Of course, real implementation should avoid factorisation completely. 

Side note: a paper [on smooth numbers](http://www.dms.umontreal.ca/~andrew/PDF/msrire.pdf), especially Ch. 5.7.

**Comment by grandpascorpion** [comment]
I have something that can do that (from a Project Euler solution)  Where
should do you think it should be added?  I don't know of a smart way using
this sort of algorithm to generate all of the numbers below the lower bound
in order to exclude them.  There is an efficient internal routine to merge
the lists of lists.  Any culling would have to occur in there. Also,
there's probably a better name than smooth.  Open to suggestions :)

smooths :: (Integral a) => [a] -> [a]

smooths pl -- returns an infinite, lazily evaluated list

smoothRange :: (Integral a) => [a] -> a -> a -> [a]

smoothRange pl lo hi = takeWhile (<= hi) $ dropWhile(<= lo) $ smooths pl

Example:

*Main> take 50 $ smooths [2, 7,
17][1,2,4,7,8,14,16,17,28,32,34,49,56,64,68,98,112,119,128,136,196,224,238,256,272,289,343,392,448,476,512,544,578,686,784,833,896,952,1024,1088,1156,1372,1568,1666,1792,1904,2023,2048,2176,2312]

**Comment by Bodigrim** [comment]
Wow, sounds nice. It is probably worth of a separate module `Math.NumberTheory.SmoothNumbers`. A function may be called `smooth` or `smoothOverSet` (following the term from [wiki](https://en.wikipedia.org/wiki/Smooth_number#Smooth_over_a_set_A)). You are welcome to prepare a PR.

**Comment by grandpascorpion** [comment]
Ooh, I like smoothOverSet.  I guess we could do something similar with
smoothOverList (which would need to sort the "nub").
I was thinking only primes would be allowable as input but the wiki page
used values which are not always prime.   If we were validating the input,
I think we could reject a set/list that had any two members which were not
relatively prime.  So (4,3, 5) would be allowed but not (4, 3, 15).
Otherwise,

I think smooth itself could take a single parameter.

So, smooth 23 would generate numbers that were 23-smooth which I think is
intuitive.  It would call the same underlying function.

**Comment by Bodigrim** [comment]
Good, I agree with the proposed interface.

**Comment by grandpascorpion** [comment]
Sorry, I had one other thought.

Using the convention of the wiki page,  would 16 be smooth over the set {4,
3} but not 8?  8 is still a multiple of 4 that doesn't use another prime
factor.  It seems like a bit of a gray area.

Thanks

**Comment by Bodigrim** [comment]
It is sensible to stick to the convention on the cited wiki page, unless we have a good reason to do it in another way. Yes, wiki does not consider 16 to be smooth over {8, 3}.

**Comment by grandpascorpion** [comment]
Agreed, thanks

**Comment by grandpascorpion** [comment]
Sorry, I let this drop on the floor.  Should this script be part of the
test-suite?

Best, Fred

**Comment by Bodigrim** [comment]
Well, it is always nice to have tests. But we can start without them as well.

**Comment by Bodigrim** [comment]
@grandpascorpion any chance for pull request?

**Comment by grandpascorpion** [comment]
Done

Thanks

**Comment by Bodigrim** [comment]
Done in #91
